### ISSUE TITLE
Config warning: import has been deprecated; use general.import instead

### ISSUE THREAD

**Issue by vdegenne** [andrewberty/alacritty-themes#1]
Recent Alacritty update causes this message to appear:

![image](https://github.com/user-attachments/assets/9fd79676-8033-405e-b731-07c8cfae2b30)

**Comment by andrewberty** [comment]
Hello Valentin,

Thank you for your time patching the deprecated import. Just merged.

Happy Coding 🙌🏼

**Comment by vdegenne** [comment]
Cool man thanks,
when you have time don't forget to publish the new version on npm.

**Comment by andrewberty** [comment]
Just did, Enjoy flicking through hundrends of themes 🧑🏼‍🎨
